### ISSUE TITLE
bootstrap.sh toolkit run file checksum fails

### ISSUE THREAD

**Issue by freecurve** [nbcrrolls/cuda#3]
That pretty much explains it, the checksum for the cuda toolkit binary fails.  Assuming there's no other files coming after the toolkit from google drive that get cut off, I bravely put a fresh toolkit binary into the appropriate directory, which resulted in the next issue...

BTW thank you very much, this roll is very nice. I am still using the older version!

**Comment by nadyawilliams** [comment]
You can put a binary with a different version or the same one. From whatever resources you have
into the roll directory where it expects find the sources. Keep in mind the binary name and version have to conform to what is written in version.mk. If you version differs just update to what you have. This stands for both, toolkit and driver.
