### ISSUE TITLE
make fails on cuda toolkit bundling

### ISSUE THREAD

**Issue by freecurve** [nbcrrolls/cuda#4]
So before I pursue this any further - it's a repeatable issue - is there any way to go through the process without bundling the cuda toolkit? Ours is available via NFS anyhow, and the fresh drivers are the most important thing. 

Thank you!

**Comment by nadyawilliams** [comment]
I don't see what errors do you have. Once you download the binaries or bring them from another source and update the ver sions accordingly the  makefile works. Keep in mind that what goes inside the version differs sometimes too much form 7 to 8, etc so you might need to edit the makefile. For the same version of the toolkit it should be straight forward and no change, for the driver different version also no change in makefile.

**Comment by freecurve** [comment]
Hi Nadya - 

I located the problem. Somewhere in your install you are expecting the toolkit runfile to be cuda_XXX_linux-run whereas they come down from NVIDIA cuda_XXX_linux.run so that was the issue. I've made a link with the linux-run ending and the 'make' works perfectly.
