### ISSUE TITLE
nvidia toolkit runfile extension issue diagnosed

### ISSUE THREAD

**Issue by freecurve** [nbcrrolls/cuda#5]
Hi - 

It seems the install procedure expects the toolkit file to be named cuda-XXX_linux-run and they come down as cuda-XXX_linux.run 
The rules look to be in /cuda/src/nvidia-toolkit/version.mk but I am not experienced enough with make etc. to fix the issue, my apologies. 

Once a symlink with the expected extension is made, the make procedure completes successfully. 

Sorry to keep bugging you, but at least people are using your code and are very appreciative :-)

Thank you.

**Comment by nadyawilliams** [comment]
HI,
this has been fixed on Mar 13. You can go through commits on  src/nvidia-toolkit/version.mk and verify. 
The "." was used in naming schema by cuda  for toolkit 7, in toolkit 8 they changed it to "-". TOOLKIT_DISTRO variable in version.mk  file takes care of it. you may have an older version of checkout. Do a git pull to update.

**Comment by freecurve** [comment]
Hmmm I just downloaded an 8.0 toolkit and it's cuda_8.0.61_375.26_linux.run this is for CentOS so not sure you are 100% correct on this, maybe their naming varies for different distros. 

From CUDA site: 
Installation Instructions:
--
Run `sudo sh cuda_8.0.61_375.26_linux.run`Follow the command-line prompts
